*** 柳絮拼音，中原官話

Modeled on /Zhung/, /the Lessing-Othmer-System/ and /Wade--Giles system/ etc, by Yuanchen Xie.

中原官話拼寫方案，仿照[[https://github.com/lotem/brise-zhung][《中州羅馬字》]]、
[[http://zh.wikipedia.org/wiki/%E5%BE%B7%E5%9C%8B%E5%BC%8F%E6%8B%BC%E9%9F%B3][德語式拼音]]
和
[[http://zh.wikipedia.org/wiki/%E5%A8%81%E5%A6%A5%E7%91%AA%E6%8B%BC%E9%9F%B3][威妥瑪拼音]]
等進行設計，主要修改塞擦音、齦顎音部分。

甲午年九月廿九，霜降前夜，方案名由 /仿德語式拼音中原官話/ 更改爲 /樹式拼音中原官話/ 。

甲午年丑月十六，小寒，學習音韻學之後，深感初製方案未分清濁，考慮不周。決定方案功能不再更新，僅不定時對詞庫等作出優化補充。再次更名爲 /柳絮拼音中原官話/ 。

樹乃統稱，柳絮爲特指，故「樹」之名宜另作他用，柳絮典出「未若柳絮因風
起」；又深慕嶺南寒柳堂，故名。

甲午年臘月十五，立春前夜，整理所有所用 RIME 方案，變更項目鏈接。

**** 優劣

  - 區分尖團音，亦可兼容。
  - 輸入時不引入26個英文字母以外的符號，顯示時加入了「ü」，便於輸入及辨認。
  - 輸入時，音節「yu」可以自動轉寫爲所表示的發音ㄩ（ü）。
  - 本方案本着讀音儘量相近的原則，解決了用「q」、「x」表示「ㄑ」、「ㄒ」時，語音與歐羅巴讀音普遍相去較遠的問題。
  - 沒有使讀音與字母儘量一一對應，完整編碼仍較長。
  - 以「d」「t」作爲不送氣與送氣音的標識等，與 IPA 的寫法不一致。
  - 未能周密考慮清濁的問題。

**** 拼寫規則

***** 聲母

鼻音ㄇ、ㄋ， 塞音ㄅ、ㄆ、ㄉ、ㄊ、ㄍ、ㄎ， 邊音ㄌ， 均与 /中州羅馬字/ 及 /漢語拼音方案/ 相同，分別表示爲
| ㄇ | m |
| ㄋ | n |
| ㄅ | b |
| ㄆ | p |
| ㄉ | d |
| ㄊ | t |
| ㄍ | g |
| ㄎ | k |
| ㄌ | l |

塞擦音以「d」標識不送氣音，「t」標識送氣音。注音符號、漢語拼音方案及本方案對應如下：
| ㄗ | z  | ds    |
| ㄘ | c  | ts    |
| ㄓ | zh | dsh   |
| ㄔ | ch | (t)ch |
| ㄐ | j  | (d)j  |
| ㄑ | q  | tj    |

擦音ㄈ、ㄙ、ㄕ、ㄖ、ㄏ，分別表示爲
| ㄈ | f    |
| ㄙ | s    |
| ㄕ | sh   |
| ㄖ | r(h) |
| ㄏ | h    |

齦顎音ㄒ表示爲 hs

ㄓ、ㄔ、ㄕ單獨構成音節時，分別用 dshih、tchih、shih 表示。

總結如下：
[[https://mmbiz.qlogo.cn/mmbiz/YhrvYGbj8X3sdN9jRUdXicDx0yq3FjyJ2EGOib9PKGJha3SpvDHia444NiayazAgb4osYF9uEtxMLbPFlYiaufQJ93w/0]]

每一格中四角分別爲：
| 本方案   | 國際音標（IPA） |
| 注音符號 | 漢語拼音        |


***** 韻母

ㄚ、ㄛ、ㄜ、ㄨ分別表示爲
| ㄚ | a |
| ㄛ | o |
| ㄜ | e |
| ㄨ | u |

ㄧ（i）表示爲「i」，無聲母時，轉寫爲「y」；其餘介母爲「ㄧ」的均以此類推。

ㄩ（ü）表示爲「yu」，無論在音節中處於何處，均寫作「yu」，顯示時自動轉寫爲「ü」；「ㄧㄡ」不簡化爲
iu，寫作 iou，無聲母時作
you。輸入及反查時，「yu」自動轉寫爲「ü」，但實際輸入的編碼不變。

ㄝ（ê）表示爲「eh」，其中「h」與在「hs-」及「-ih」中的作用類似，以表送氣爲主。

**** 聲調

可以用符號 =; / < \= 輸入聲調，雖調值雖不盡相同，習慣依 /漢語拼音方案/ ；如輸入 =a= ，則字母分別轉寫爲 =ā á â à= ，其餘類推。

**** 鍵盤佈局

採用 qwerty 鍵盤佈局。

**** Tips

  - 輸入ㄔ、ㄐ、ㄖ時，可以不輸入完整拼法 tch、dj、rh，分別簡化爲 ch、j、r。
  - 聲母爲齦顎音ㄐ、ㄑ、ㄒ時，可以不鍵入介母ㄧ（i）。如「九」，本方案爲「djiou」，可簡化爲「jou」；「強」，本方案爲「tjiang」，可簡化爲「tjang」；「下」，本方案爲「hsia」，可簡化爲「hsa」。
  - 完整拼寫區分尖團音，也可簡化輸入達到兼容的目的。如「年輕」與「青年」，分別爲「nian'tjing」與「tsing'nian」，不確定尖團時，可輸入「nian't」與「t'nian」達到兼容尖團音的效果；同樣，「精神」與「神經」，可分別從「dsing'shen」、「shen'djing」簡化爲「d'shen」與「shen'd」；ㄙ和ㄒ的編碼仍有待優化。
  - 利用「z」、「c」、「q」、「x」三個按鍵作爲「ㄗ（ds）」、「ㄘ（ts）」、「ㄑ（tj）」、「ㄒ（hs）」四個音的替代方案。

**** 歡迎共同討論
